#!/bin/bash

packages=(
    "1password-cli"
    "1password"
    "bat"
    "brave-browser"
    "chromium"
    "clamav"
    "cmake"
    "code"
    "firewall-config"
    "flatpak"
    "fzf"
    "gh"
    "git-subtree"
    "git"
    "helix"
    "htop"
    "inkscape"
    "jq"
    "lynis"
    "neovim"
    "openh264"
    "python3-neovim"
    "ripgrep"
    "ShellCheck"
    "trash-cli"
    "VirtualBox"
    "wireguard-tools"
    "wireshark"
    "xclip"
)
package_groups=(
    "C Development Tools and Libraries"
)
packages_flatpak=(
    "com.spotify.Client"
    "io.beekeeperstudio.Studio"
    "org.getzola.zola"
    "org.gnome.gedit"
)

if [ "$(command -v dnf)" ]; then
  # Fedora
  sudo dnf update --refresh -yq
  sudo dnf install dnf-plugins-core -yq

  # Configure

  # Flatpak
  sudo dnf config-manager --add-repo https://dl.flathub.org/repo/flathub.flatpakrepo
  # VSCode
  sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
  sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  # 1Password
  sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
  # Brave
  sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
  sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  # VirtualBox
  sudo dnf config-manager --add-repo https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
  sudo rpm --import https://www.virtualbox.org/download/oracle_vbox_2016.asc
  # GitHub CLI gh
  sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo

  # Install
  sudo dnf install "${packages[@]}" -yq
  sudo dnf group install "${package_groups[@]}" -y
  sudo flatpak install flathub "${packages_flatpak[@]}" -yq
  # Check installation
  for package in "${packages[@]}"; do
    dnf repoquery --installed "$package"
  done
elif [ "$(command -v apt)" ]; then
  # Ubuntu (not tested)
  sudo apt install "${packages[@]}" -yq
else
  echo "Incompatible package manager, only dnf (Fedora) and apt (Ubuntu) are supported" >&2
  exit 1
fi

# Docker rootless mode
curl -fsSL https://get.docker.com/rootless | sh
# Nextdns
sh -c "$(curl -sL https://nextdns.io/install)"
# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# Go
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
