live_config_reload = true

[window]
dimensions = { columns = 120, lines = 40 }
position = { x = 0, y = 0 }
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
opacity = 1
title = "💀"
dynamic_title = false
decorations_theme_variant = "dark"

[font]
size = 9

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[mouse]
  hide_when_typing = true
  bindings = [
    { action = "PasteSelection", mouse = "Middle" },
    { action = "CopySelection", mouse = "Right" },
  ]

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = "Block"
blink_interval = 300
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[keyboard]
bindings = [
    { key = "Escape", mods = "Control", action = "ToggleViMode" },
    { key = "I", mode = "Vi|~Search", action = "ToggleViMode" },
    { key = "N", mods = "Control|Shift", action ="CreateNewWindow" },
]


[colors.cursor]
text = "CellBackground"
cursor = "#ff0000"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

## Tomorrow Dark
[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[colors.normal]
black = "0x1d1f21"
red = "0xcc6666"
green = "0xb5bd68"
yellow = "0xf0c674"
blue = "0x81a2be"
magenta = "0xb294bb"
cyan = "0x8abeb7"
white = "0xc5c8c6"

[colors.bright]
black = "0x969896"
red = "0xcc6666"
green = "0xb5bd68"
yellow = "0xf0c674"
blue = "0x81a2be"
magenta = "0xb294bb"
cyan = "0x8abeb7"
white = "0xffffff"

